### ISSUE TITLE
Sugestões de mudanças na UI da página de resultados

### ISSUE THREAD

**Issue by victorsenam** [prefeiturasp/SME-FilaDaCreche#27]
Eu sugiro algumas mudanças na UI especificamente da [página de resultados](http://filadacreche.sme.prefeitura.sp.gov.br/#/resultados/27/-46.731517199999985/-23.5605778/R.%20do%20Mat%C3%A3o%20-%20Butant%C3%A3,%20S%C3%A3o%20Paulo%20-%20SP,%2003178-200,%20Brasil). Aqui vai um screenshot de como ela está agora.
![screenshot from 2018-08-31 13-20-47](https://user-images.githubusercontent.com/3386440/44925885-08097480-ad26-11e8-86b6-1dd5dfb520aa.png)
- Primeiro, eu acho que o título contém informação demais. A pessoa já sabe que está buscando para um tal endereço e tal grupo e essa informação fica numa fonte grande logo no começo da página quando ela é provavelmente ignorada. Acredito que isso canse o usuário e deixa a experiência mais confusa, leva ao usuário ao hábito de ignorar texto importante no resto da aplicação. Sugiro que a gente mude para algo mais ou menos assim:
![screenshot from 2018-08-31 13-24-47](https://user-images.githubusercontent.com/3386440/44927201-017cfc00-ad2a-11e8-901b-c94f79450fa9.png)
Isso deixa todas as informações anteriores ali e mantém a mesma explicação sobre a fila que existia antes, mas prioriza e cansa menos.
- A data da atualização de dados que está no fim da página pode ficar no banner mesmo, no texto pequeno, na minha opinião. Isto é, em vez de colocar "* Dados atualizados em 30/08/2018 04:06" no fim da listagem das creches, colocar "Há 65 crianças na fila do Mini Grupo I a serem distribuídas nas 11 creches perto de R. do Matão - Butantã, São Paulo - SP, 03178-200, Brasil. Estes dados foram atualizados em 30/08/2018 04:06." logo no cabeçalho. Mantém todas as informações em um lugar só e limpa uma linha de informação "secundária" da listagem.
- Não entendo o porque do subtítulo "CRECHE" antes da listagem. Poderíamos tirá-lo.
- Na página de cadastro, adicionamos mudamos as informações disponibilizadas sobre as creches. Acho que isso é confuso para o usuário e, se ele tem interesse em recuperar a informação que viu em uma destas páginas, por elas serem tão parecidas, vai tentar fazer em qualquer uma e falhar, o que gera frustração. Acho que deveríamos deixar isso consistente entre as duas páginas e, preferencialmente, usar o mesmo componente no react. Pelo código, me parece que se a escola tem um número de telefone, ele é mostrado só na [página de registro](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/09b0563bb427734932d987448b2e552ddabcf81d/src/containers/Register/RegistrationList.js#L19) e não na [página de resultados](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/09b0563bb427734932d987448b2e552ddabcf81d/src/containers/Results/SchoolList.js#L27). O mesmo acontece com o tipo de escola.
![screenshot from 2018-08-31 14-36-05](https://user-images.githubusercontent.com/3386440/44927540-42c1db80-ad2b-11e8-9ec9-52d453f4e7b2.png)

**Comment by bplmp** [comment]
@victorsenam estou de acordo com todos os pontos, mas acho que vale discutir melhor o último:

O principal motivo para mostrar informações diferentes é o seguinte:

- Os responsáveis podem cadastrar a criança em qualquer tipo de unidade escolar, mesmo aquelas que oferecem ensino fundamental mas não ensino infantil. Logo a ideia é que a página de registro mostrasse todas as unidades e a de resultado filtrasse só as creches (embora eu não tenha certeza agora se estamos apresentando esse dado dessa maneira, é algo que preciso checar na API).

Uma possível solução é mostrar a lista de creches somente no momento na página de registro / cadastro, como na imagem abaixo:

![image](https://user-images.githubusercontent.com/11858154/44987635-3e313900-af5e-11e8-8862-5e13592f78ff.png)

... ao mesmo tempo sinto que fica agora faltando uma informação importante nessa página. O que acham, @victorsenam e @ludimila ?

**Comment by victorsenam** [comment]
Boa! Acho legal esperar um feedback da @ludimila sobre os primeiros pontos antes de criar issues pra eles, certo?
Então, só pra ver se entendi, na verdade, a página de registro pode mostrar mais instituições do que a página de resultados? A pessoa vai ver todas as instituições, mesmo aquelas que não possuem ensino infantil na página de registro? Não entendo o porque. É porque aquela unidade pode acabar abrindo uma vaga de creche no futuro?
Bom, isso não é um problema gravíssimo, mas eu acho que esse tipo de comportamento é um pouco confuso. Na visão do usuário essas duas páginas são idênticas, certo? Não fica muito claro qual é qual e o motivo de informações diferentes aparecerem e, por causa disso, se um usuário for buscar alguma informação que viu em alguma delas, pode se confundir bastante e isso pode gerar uma frustração. Pra mim, já que elas são tão parecidas, o ideal pro usuário é que elas fossem idênticas.
Se a gente quer mostrar informações diferentes nelas por qualquer motivo, talvez seja uma boa ideia tentar esclarecer bem esse motivo e tentar discutir uma forma melhor.

**Comment by victorsenam** [comment]
Acho que isso se relaciona bem com a #22 também, dependendo das informações adicionais, essa discussão muda.

**Comment by bplmp** [comment]
@victorsenam acho que expliquei mal: os responsáveis podem utilizar qualquer unidade para fazer o cadastro na fila de espera. A partir desse momento eles passam a esperar por uma vaga nas unidades próximas do endereço de cadastro. Ou seja, posso ir numa escola que tem fundamental só e cadastrar uma criança para a fila do ensino infantil. Pelo menos é isso que entendo do processo.

Concordo que é confuso ter a mesma informação em dois lugares, por isso talvez a lista de escolas / creches devesse estar só na [página de cadastro](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/09b0563bb427734932d987448b2e552ddabcf81d/src/containers/Register/Register.js).

**Comment by ludimila** [comment]
@bplmp eu acho que a gente pode se desprender um pouco dessa tela desse tamanho, se ela for maior a informação pode ficar melhor posicionada se a pessoa estiver no computador, no celular a gente deixa responsivo (e o problema de excesso/falta de informação permanece). Eu concordo com o pontos levantados pelo @victorsenam

**Comment by bplmp** [comment]
@ludimila eu acho que a gente precisa resolver primeiro pra mobile, estamos em quase 70% de usuários mobile no site...

**Comment by victorsenam** [comment]
Legal @bplmp! Entendi o motivo da diferença agora e concordo que deixar os dois iguais não parece perfeito. Que tal criarmos issues para implementar as outras sugestões e uma outra para discutir mais essa solução para que isso não nos bloqueie por enquanto?

**Comment by bplmp** [comment]
@victorsenam acho que é o ideal mesmo, fazer esse último ponto mais difícil e polêmico como uma issue separada. 

Eu acho que outros pontos sobre o texto do título, onde mostra quando foram atualizados os dados e etc. já podem ser implementados.

**Comment by victorsenam** [comment]
Separei as issues. Vou fechar isso aqui.
