### ISSUE TITLE
Implementar mudanças de UI na página de resultados

### ISSUE THREAD

**Issue by victorsenam** [prefeiturasp/SME-FilaDaCreche#34]
Algumas sugestões feitas na issue #27 foram aceitas e podem ser implementadas. São elas:
- [x] Alterar o título para que ele contenha menos informações (primeiro item das sugestões)
- [x] Mudar a localização da data de atualização das informações (segundo item)
- [x] Remover o cabeçalho "CRECHES" (terceiro item)

**Comment by bplmp** [comment]
Obrigado @victorsenam!
