### ISSUE TITLE
Resolver lint warnings

### ISSUE THREAD

**Issue by victorsenam** [prefeiturasp/SME-FilaDaCreche#45]
Quando eu rodo `npm run` localmente eu recebo vários lint warnings. Acho muito interessante evitar isso e suprimir os warnings inúteis com ``// eslint-disable-next-line``. Evitar que existam linter warnings evita que nós criemos novos warnings e faz com que a qualidade do código se mantenha boa constantemente.

```
Compiled with warnings.

./src/containers/Results/Results.js
  Line 1:   'Component' is defined but never used  no-unused-vars
  Line 2:   'Router' is defined but never used     no-unused-vars
  Line 2:   'Route' is defined but never used      no-unused-vars
  Line 8:   'Spacer' is defined but never used     no-unused-vars
  Line 16:  Expected '===' and instead saw '=='    eqeqeq

./src/containers/Register/Register.js
  Line 1:  'Component' is defined but never used  no-unused-vars

./src/containers/CheckIfRegistered/CheckIfRegistered.js
  Line 1:  'Component' is defined but never used  no-unused-vars

./src/containers/IsRegistered/IsRegistered.js
  Line 1:  'Component' is defined but never used  no-unused-vars

./src/containers/DateOfBirthForm/DateOfBirthForm.js
  Line 1:  'Component' is defined but never used  no-unused-vars

./src/containers/AddressInput/AddressInput.js
  Line 1:  'Component' is defined but never used  no-unused-vars

./src/containers/Home/Home.js
  Line 1:  'Component' is defined but never used  no-unused-vars
  Line 5:  'Logo' is defined but never used       no-unused-vars

./src/containers/PreschoolGroup/PreschoolGroup.js
  Line 2:   'Router' is defined but never used  no-unused-vars
  Line 2:   'Route' is defined but never used   no-unused-vars
  Line 13:  Missing radix parameter             radix
  Line 14:  Missing radix parameter             radix

./src/App.js
  Line 2:   'Router' is defined but never used   no-unused-vars
  Line 2:   'Link' is defined but never used     no-unused-vars
  Line 18:  'GLOBALS' is defined but never used  no-unused-vars
  Line 19:  'API' is defined but never used      no-unused-vars

./src/containers/DateOfBirthForm/SelectDate.js
  Line 2:   'Router' is defined but never used                 no-unused-vars
  Line 2:   'Route' is defined but never used                  no-unused-vars
  Line 6:   'GLOBALS' is defined but never used                no-unused-vars
  Line 49:  Missing radix parameter                            radix
  Line 50:  Missing radix parameter                            radix
  Line 68:  'dateSelected' is assigned a value but never used  no-unused-vars

./src/components/ContinueButton.js
  Line 2:  'Router' is defined but never used  no-unused-vars
  Line 2:  'Route' is defined but never used   no-unused-vars

./src/components/Logo.js
  Line 3:  'logo' is defined but never used  no-unused-vars

./src/containers/AddressInput/AddressForm.js
  Line 4:  'Router' is defined but never used  no-unused-vars
  Line 4:  'Route' is defined but never used   no-unused-vars

./src/components/Footer.js
  Line 6:  'footerMob' is defined but never used   no-unused-vars
  Line 7:  'footerDesk' is defined but never used  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

**Comment by bplmp** [comment]
De acordo @victorsenam! O problema é que alguns desses warnings são falsos, especialmente os `'Router' is defined but never used`, relativos ao router.

Da última vez que tentei limpar todas essas variáveis não usadas eu acabei quebrando a aplicação, então precisamos entender pq ela depende de variáveis que o linter intende como não usadas.

**Comment by bplmp** [comment]
@victorsenam fiz merge no https://github.com/prefeiturasp/SME-FilaDaCreche/pull/46#pullrequestreview-155485822

Resolveu vários erros. Você se dá melhor com o linter que eu :smile:.

Agora eu vejo só:

    Line 13:  Missing radix parameter  radix
    Line 14:  Missing radix parameter  radix

    ./src/containers/Results/Results.js
    Line 15:  Expected '===' and instead saw '=='  eqeqeq

    ./src/containers/DateOfBirthForm/SelectDate.js
    Line 48:  Missing radix parameter  radix
    Line 49:  Missing radix parameter  radix

Esse `Line 15:  Expected '===' and instead saw '=='  eqeqeq` eu acho que é melhor deixar assim pelo menos por enquanto, por não termos garantia se o dado virá da API como string ou integer.

**Comment by victorsenam** [comment]
Beleza, se a gente tem medo desse `===` ele é um bom caso da dar disable. Essa coisa de falhar ao apagar o `Router`, eu tinha mudado, por exemplo, a linha
`import { BrowserRouter as Router, Route, Link, HashRouter } from 'react-router-dom';`
para
`import { BrowserRouter as Route, Link, HashRouter } from 'react-router-dom';`
em vez de
`import { Route, Link, HashRouter } from 'react-router-dom';`
e isso tinha me confundido bastante, achei que não estava funcionando, mas é que na real eu tinha feito errado. Talvez você tenha cometido o mesmo erro quando pensou que não fosse funcionar arrumar os warnings.
