### ISSUE TITLE
Rota /cadastrar quebrada

### ISSUE THREAD

**Issue by bplmp** [prefeiturasp/SME-FilaDaCreche#58]
Alguma mudança quebrou a rota `/cadastrar`.

Erro:

    new SchoolList
    src/components/SchoolList.js:13
      10 | constructor(props) {
      11 |   super(props);
      12 |   this.state = {
    > 13 |     displayedListSize: props.shortenList
      14 |       ? Math.min(shortenedListSize, props.schools.length)
      15 |       : props.schools.length,
      16 |   };

@victorsenam precisamos achar o que quebrou isso. Vou começar a investigar agora. Está quebrado em produção inclusive.

**Comment by bplmp** [comment]
`ResultsLoaded.js` parece que não está passando o `state` corretamente para `SchoolList.js`, nessas linhas:

      <Link to={{
        pathname: STRINGS.routes.register + "/" + props.groupCode,
        state: {schoolsNearby: props.schoolsNearby},
      }}>

**Comment by bplmp** [comment]
Eis o commit que quebrou nosso código: 320f724f6eb7d725d856c702a52657ed3dc5fcf5

**Comment by bplmp** [comment]
Isso conserta: 2f465242d16146d06f800d2c3d40a756c86e4615. Não sei bem porque, a ser investigado. @victorsenam talvez entenda porque este commit quebrou: https://github.com/prefeiturasp/SME-FilaDaCreche/commit/320f724f6eb7d725d856c702a52657ed3dc5fcf5.

**Comment by victorsenam** [comment]
Vou investigar a causa sim.

**Comment by victorsenam** [comment]
[Faltou um return](https://github.com/prefeiturasp/SME-FilaDaCreche/pull/53/files#diff-7294237b1a0d2388446eb41e46143429R52). Que loucura. Eu devo ter testado esse PR errado. Peço desculpas, vou tomar mais cuidado.
Vou submeter um outro PR que aplica aquela mudança corretamente.
