### ISSUE TITLE
Transformar componentes com estado (stateful) em componentes sem estado (stateless)

### ISSUE THREAD

**Issue by Rahmon** [prefeiturasp/SME-FilaDaCreche#6]
Os componentes que estão na pasta "components" são do tipo stateful (com estado) e a maioria não gerencia um estado interno (local state) e não faz uso dos métodos de ciclo de vida do componente. Dessa forma, é interessante fazer uma refatoração para transformá-los de "stateful" para "stateless".

Apesar dessa mudança não impactar a perfomance da aplicação, componentes sem estado são mais fáceis de serem entendidos (já que são apenas funções que recebem uma entrada e retornam uma saída) e testados. O ideal é sempre iniciar com um componente sem estado e quando surgir a necessidade refatorar para um componente com estado.

Abaixo segue a lista dos arquivos que podem passar por essa mudança:

- [x] [Alert.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/Alert.js)
- [x] [BackButton.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/BackButton.js)
- [x] [Banner.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/Banner.js)
- [x] [CollapseButton.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/CollapseButton.js)
- [x] [ContinueButton.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/ContinueButton.js)
- [x] [DefaultButton.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/DefaultButton.js)
- [x] [Footer.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/Footer.js)
- [x] [HomeBanner.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/HomeBanner.js)
- [x] [Logo.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/Logo.js)
- [x] [Spacer.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/Spacer.js) 
- [x] [SubBanner.js](https://github.com/prefeiturasp/SME-FilaDaCreche/blob/master/src/components/SubBanner.js)

Para quem for contribuir nessa issue: 

- faça para cada arquivo um PullRequest (PR) separado pois assim fica mais fácil para testar e analisar os impactos da mudança
- referencie essa issue para saber quais arquivos já foram alterados

Essa refatoração é simples e ideal para quem está começando com React.

**Comment by Rahmon** [comment]
@bplmp 

Achei os argumentos "contras" com pouca sustentação. Tanto que se você ler os comentários você vai ver que a maioria é contra os "contras"...rs. Até mesmo o autor do artigo diz no final (e nos comentários que ele respondeu tem mais coisas): _I’m still a fan of functional components_. 

Sobre a inconsistência de código, acho que é mais fácil para um novato entender uma função (stateless) do que uma classe (que é um conceito de OO).

De qualquer forma, a discussão se vale a pena mudar ou não, é válida.

**Comment by bplmp** [comment]
@Rahmon sim, não são muito sustentáveis os argumentos realmente, pra mim o único que continua valendo é o da inconsistência.

Concordo que é mais fácil pra um novato entender uma simples função JS (apesar de que, para mexer nesse código, alguma hora ele/ela vai precisar entender classes ES6). 

Mas me incomoda (bastante) a sintaxe ser diferente pra duas coisas que eu vejo como iguais. Quer dizer: se o componente sem estado é um caso específico do componente com estado (é assim que eu vejo), por que a sintaxe dele deve ser bastante diferente? Eu prefiro o jeito mais verboso pq ele cobre os dois casos igualmente.

Mas eu vou passar essa bola pra @ludimila e a equipe que vai manter esse código em produção, acho que a decisão final é deles!

**Comment by ludimila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Teste](https://trello.com/c/MkVdxe7D/1-teste)

**Comment by victorsenam** [comment]
Olá! Como talvez tenha dado pra perceber, estou trabalhando nesta issue. Como eu comentei em #15, alguns desses estados tem props não tipadas. Posso já tipar elas aproveitando que estou fazendo estas mudanças?

**Comment by Rahmon** [comment]
@victorsenam 

Talvez seja interessante criar um issue e fazer um levantamento dos componentes que têm props não tipadas (parecido com o que eu fiz nessa issue). Dessa forma, fica mais fácil para outras pessoas contribuirem também. Mas essa é apenas uma ideia.. ;)

**Comment by bplmp** [comment]
@victorsenam sim, pode adicionar os types para os props onde achar. [Referência sobre](https://reactjs.org/docs/typechecking-with-proptypes.html).

Acredito que você não vai encontrar quase nada com types no código atualmente.

**Comment by victorsenam** [comment]
Beleza! Por enquanto vou adicionando enquanto encontrar, se rolar uma preocupação maior em tipar tudo eu posso investigar mais e abrir uma issue nova depois.

**Comment by victorsenam** [comment]
Feito :)
