### ISSUE TITLE
Implementar testes de componentes

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-FilaDaCreche#8]
Teste Unitário dos componentes.

**Comment by victorsenam** [comment]
Estou implementando testes unitário das `utils` que ainda não têm.

**Comment by bplmp** [comment]
@victorsenam vi que estão testando um CI acho que aqui: https://gitlab.com/victorsenam/SME-FilaDaCreche/-/jobs/94606944

Estou achando que esse teste falhou por falta das .env vars. Depois explica pra nós como está fazendo a CI / testes?

**Comment by bplmp** [comment]
Mas os testes que falharam são os das utils que já existiam antes, e eles não falham aqui quando estou desenvolvendo localmente.

Parece que eles falham por não encontrar os módulos do app, eu acho que é porque falta o `NODE_PATH='src/'`. Me explica melhor como você tá fazendo o CI no GitLab?

**Comment by victorsenam** [comment]
Sim, sim, eu vi. Eu quis dizer que a minha configuração do CI estava incompleta. Eu estava só testando o que acontecia quando eu ligava o "Auto DevOps" e deixava rolar. Não esperava que ele fosse ficar marcando os commits daqui como falhos se os testes caíssem. Enfim, faz todo sentido os testes terem falhado e certamente é culpa da configuração das `.env`.
Acho inclusive que talvez seja mais fácil que algum de vocês faça o CI, já que eu nunca deployei esse código, e nem posso, acho. Me avisa se concordar que paro de me preocupar com isso, mas posso tentar mais se quiserem.

**Comment by bplmp** [comment]
Certo. Na minha opinião, seria mais interessante você focar nos testes e a gente tentar cuidar dessa parte de CI e deploy. @ludimila de acordo?

**Comment by ludimila** [comment]
@bplmp não concordo, mas também não acho que o CI seja prioridade no momento, era mais pra ser um beta e ver se valeria a pena migrar para o CI do gitlab.

**Comment by bplmp** [comment]
@ludimila ou seja, você acha que nenhum dos dois (testes e CI) são prioridade no momento?

Eu acho testes importantes pra gente conseguir agilizar a aceitação dos pull requests sem ter que checar as funcionalidades 100% manualmente.

**Comment by ludimila** [comment]
Os testes podem manter.

**Comment by ludimila** [comment]
Escrevi testar componentes apenas para os testes unitários não serem confundidos com os de e2e. Eu particularmente estou mais familiarizada com testes e2e e acho que seria mais simples para outras pessoas continuarem do ponto onde você parar. Eu ficaria com a opção 1 ou  2. @bplmp o que acha?

**Comment by victorsenam** [comment]
Ah, acho que não ficou claro. Eu quis dizer que, na minha opinião, os testes e2e são essenciais e, se quisermos testar mais do que isso, sugiro que sigamos pelas opções 2 e 3.

**Comment by bplmp** [comment]
@victorsenam desculpa a demora. O item 1 estamos em progresso, certo?

Eu não sou especialista no assunto, mas me parece que o 3 é mais interessante que o 2, uma vez que boa parte dos ganhos em usar testes snapshot já está coberto em teste e2e, certo? Me corrija se eu tiver viajado.

**Comment by victorsenam** [comment]
Eu concordo, o 3 está me parecendo mais útil agora, ele agiliza bastante o processo todo de produzir código, melhora muito a clareza e evita muita bobagem.
Snapshots são testes unitários, os coitados nunca são uma prioridade.

**Comment by ludimila** [comment]
Então o próximo passos é tornar o js tipado?  Se o dev quiser passar um objeto como prop para outro componente, vai ter que criar um tipo para esse objeto dizendo quais os tipos dos campos que ele possui, ao invés de só confiar que quem implementar vai mandar o tipo certo, isso parece bom e ruim ao mesmo tempo, não vejo como isso deixa o processo mais rápido, mas pode ser que deixe com maior qualidade. Como outras pessoas que vierem a contribuir se beneficiam com isso ao invés de se desmotivar?

**Comment by victorsenam** [comment]
De fato aumenta um pouco a barreira de aprendizado, apesar de ser bastante intuitivo.
O [flow](flow.org) te permite misturar código tipado e não tipado sem problema, então a gente poderia continuar aceitando código normal, se a gente decidir que vai trabalhar assim.
O processo fica mais rápido, na minha opinião, porque a investigação do código fica muito mais simples.

Apesar disso, acho que essa discussão tá se estendendo e não é tão importante assim, vamos deixar isso de lado por enquanto? Se surgir no futuro uma vontade de tipar de novo, a gente tem aqui alguns argumentos pra considerar já.

**Comment by bplmp** [comment]
Concordo em deixar de lado por enquanto, depois pensar os reais ganhos de tipar. Como é uma aplicação que não deve crescer muito, talvez não valha a pena tipar por enquanto, na minha opinião.
